version: "3"
networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: "bitnami/zookeeper:3.7"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
    logging:
      driver: none
  kafka:
    image: "bitnami/kafka:2"
    logging:
      driver: none
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-tier
  memgraph-mage:
    build: ./memgraph
    entrypoint: ["/usr/bin/supervisord"]
    environment:
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - ./memgraph/query_modules:/usr/lib/memgraph/query_modules
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    networks:
      - app-tier
  core:
    image: tianon/true
    restart: "no"
    depends_on:
      - kafka
      - memgraph-mage
  data-stream:
    build: ./data-stream
    volumes:
      - ./data-stream:/app
    entrypoint:
      [
        "python3",
        "prices_producer.py",
        "--data-directory=prices-data",
        "--interval=1"
      ]
    environment:
      KAFKA_IP: kafka
      KAFKA_PORT: "9092"
      MEMGRAPH_IP: memgraph-mage
      MEMGRAPH_PORT: "7687"
    depends_on:
      - core
    networks:
      - app-tier
  questdb:
    image: questdb/questdb:6.6.1
    hostname: questdb
    container_name: questdb
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
    networks:
      - app-tier
    logging:
      driver: none
  questdb_kafka_consumer:
    build: ./time_series
    env_file:
      - ./.env
    environment:
      KAFKA_IP: kafka
      KAFKA_PORT: 9092
      QDB_PORT: 8812
      QDB_HOST: questdb
    networks:
      - app-tier
    depends_on:
      - questdb
      - kafka
    restart: always